"""
Questionnaire Data Module
=========================
Contains all questionnaire items for both User and Non-User groups.
Questions are stored in ordered dictionaries to maintain correct sequencing.
All question text is preserved verbatim from the validated research instrument.

Response Scale (7-point Likert):
    1 = Strongly Disagree
    2 = Disagree
    3 = Slightly Disagree
    4 = Neutral
    5 = Slightly Agree
    6 = Agree
    7 = Strongly Agree
"""

from collections import OrderedDict


# ---------------------------------------------------------------------------
# Screening
# ---------------------------------------------------------------------------
SCREENING_QUESTION = (
    "Have you ever had an emotional or personal conversation with an AI system?"
)

# ---------------------------------------------------------------------------
# Demographics
# ---------------------------------------------------------------------------
DEMOGRAPHICS = [
    {
        "id": "demo_age",
        "text": "What is your age?",
        "options": ["18-20", "21-24", "25-29", "30-34", "35+"],
    },
    {
        "id": "demo_dept",
        "text": "Which department do you belong to?",
        "options": ["Computer Science", "Engineering", "Arts & Humanities", "Sciences", "Business", "Other"],
    },
    {
        "id": "demo_year",
        "text": "What is your current year of study?",
        "options": ["1st Year", "2nd Year", "3rd Year", "4th Year", "Masters", "PhD", "Other"],
    }
]

# ---------------------------------------------------------------------------
# Likert scale anchors
# ---------------------------------------------------------------------------
LIKERT_LABELS = {
    1: "Strongly Disagree",
    2: "Disagree",
    3: "Slightly Disagree",
    4: "Neutral",
    5: "Slightly Agree",
    6: "Agree",
    7: "Strongly Agree",
}

# ---------------------------------------------------------------------------
# Section background theme mapping
# Each key maps to a CSS gradient defined in the app
# ---------------------------------------------------------------------------
SECTION_BACKGROUNDS = {
    "capability": "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    "authenticity": "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    "openness": "linear-gradient(135deg, #0a1628 0%, #134e5e 50%, #1a4040 100%)",
    "concerns": "linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 50%, #1a1a2e 100%)",
    "trust": "linear-gradient(135deg, #0a192f 0%, #112240 50%, #1a365d 100%)",
    "motivation": "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    "empathy": "linear-gradient(135deg, #0a1628 0%, #1a3a4a 50%, #1a4040 100%)",
}

# ---------------------------------------------------------------------------
# Non-User Questionnaire  (20 items)
# ---------------------------------------------------------------------------
NON_USER_SECTIONS = OrderedDict([
    ("perceived_capability", {
        "title": "Perceived Capability of AI",
        "background": "capability",
        "questions": [
            "I believe AI systems may be able to understand human emotions to some extent.",
            "I think AI might be able to provide responses that feel emotionally supportive.",
            "I believe AI could potentially comfort people during difficult or stressful situations.",
            "I think AI can simulate empathy even though it does not truly experience emotions.",
        ],
    }),
    ("perceived_authenticity", {
        "title": "Perceived Authenticity of AI Emotional Responses",
        "background": "authenticity",
        "questions": [
            "In my opinion, emotional responses generated by AI would likely feel artificial.",
            "I believe emotional support from AI cannot fully replace genuine human care.",
            "I think conversations with AI would probably feel less authentic than conversations with people.",
            "I believe AI may appear empathetic but its responses are ultimately programmed.",
        ],
    }),
    ("openness", {
        "title": "Openness Toward Emotional AI Interaction",
        "background": "openness",
        "questions": [
            "I might consider talking to AI about personal feelings in the future.",
            "I think AI could become a useful emotional support tool for some people.",
            "I am curious about how AI systems handle emotional conversations.",
            "I might feel comfortable sharing minor concerns with AI.",
        ],
    }),
    ("concerns_skepticism", {
        "title": "Concerns and Skepticism About Emotional AI",
        "background": "concerns",
        "questions": [
            "I would probably worry about privacy if someone shared emotions with AI.",
            "I believe people might become too emotionally dependent on AI.",
            "Emotional conversations with AI might reduce real human interactions.",
            "I would likely hesitate to trust emotional advice from AI.",
        ],
    }),
    ("human_trust", {
        "title": "Human-to-Human Trust",
        "background": "trust",
        "questions": [
            "I usually trust people until they give me a reason not to trust them.",
            "Trusting another person is not difficult for me.",
            "My typical approach is to trust new acquaintances until they prove I should not trust them.",
            "My tendency to trust others is high.",
        ],
    }),
])

# ---------------------------------------------------------------------------
# User Questionnaire  (49 items)
# ---------------------------------------------------------------------------
USER_SECTIONS = OrderedDict([
    ("motivation", {
        "title": "Motivation to Use AI for Emotional Interaction",
        "background": "motivation",
        "questions": [
            "I use AI because it is available whenever I need support.",
            "AI is easier to access than talking to a person.",
            "I prefer AI when I want immediate responses.",
            "I use AI because it helps me express my thoughts and emotions.",
            "I find it easier to open up to AI than to people.",
            "I use AI when I need to talk about my feelings.",
            "I feel more comfortable sharing personal things with AI.",
            "I use AI because it does not judge me.",
            "I prefer AI when I feel embarrassed to talk to someone.",
            "I use AI to feel better when I am stressed.",
            "Talking to AI gives me emotional relief.",
            "AI helps me think more clearly about my problems.",
            "I use AI because I am curious about its responses.",
            "I like exploring how AI reacts to emotional situations.",
        ],
    }),
    ("perceived_empathy", {
        "title": "Perceived Empathy of AI",
        "background": "empathy",
        "questions": [
            "The AI considered my emotional state during the interaction.",
            "The AI responded to my feelings in an appropriate way.",
            "The AI reacted sympathetically when I expressed concerns or problems.",
            "The AI showed interest in my emotional situation.",
            "The AI understood the goals I was trying to achieve.",
            "The AI understood my needs during the interaction.",
            "The AI understood what I wanted to accomplish.",
        ],
    }),
    ("perceived_authenticity", {
        "title": "Perceived Authenticity in Emotional AI Interaction",
        "background": "authenticity",
        "questions": [
            "The AI makes it clear why it responds to my emotions in the way it does.",
            "I feel the AI is open about its goals during emotional conversations.",
            "The AI seems to improve its emotional responses based on past interactions.",
            "I feel the AI remembers and adapts to my emotional style over time.",
            "The AI expresses emotions in a way that feels human-like.",
            "The AI feels like a social partner rather than just a tool when we talk about feelings.",
            "The AI's emotional responses fit naturally into the flow of conversation.",
            "The AI communicates emotions in a socially appropriate and engaging way.",
            "The AI stays consistent in its emotional tone throughout a conversation.",
            "The AI's emotional responses align with the context of what we are discussing.",
            "The AI's emotional responses feel artificial or scripted.",
            "I feel the AI interacts with me in an emotionally authentic way.",
        ],
    }),
    ("trust_in_ai", {
        "title": "Trust in AI",
        "background": "trust",
        "questions": [
            "I understand how the AI system works and I feel confident I will be able to use it in the future.",
            "I understand how the AI system behaves, how it can assist me, and what I can expect from using it in the future.",
            "The AI system consistently provides the results it is expected to produce.",
            "The AI system responds the same way under the same conditions at different times.",
            "When I need help, the AI system responds to my needs effectively and responsively.",
            "The AI system provides me with the effective and responsive help I need.",
            "I find the AI system suits my preference and I would feel a sense of loss if I could no longer use it.",
            "I like using the AI system because it suits me, and I always want to use it.",
            "I feel in control when operating the various functions and features of the AI system.",
            "The AI system has functionalities and features I can control.",
            "When I am unsure about the AI system's result, I believe in the AI system rather than myself.",
            "Even if I am not sure about the result and the actual performance, I am confident that the AI system will provide the best result.",
        ],
    }),
    ("human_trust", {
        "title": "Human-to-Human Trust",
        "background": "trust",
        "questions": [
            "I usually trust people until they give me a reason not to trust them.",
            "Trusting another person is not difficult for me.",
            "My typical approach is to trust new acquaintances until they prove I should not trust them.",
            "My tendency to trust others is high.",
        ],
    }),
])
